spring.application.name=ms-barriodigital-report

server.port=8085

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.consumer.group-id=report-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-lingering-snow-acxzqbs5-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_W4i3tNJpexlf}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true